### PR TITLE
Update relationship.php

### PR DESCRIPTION
**Pull request by MORich-1**
Updated relationship.php to allow user to view arrays regarding
relationships using newer versions of PHP.

### CODE REVIEW

**Comment by eikonos** [comment]
:+1:

**Comment by eikonos** [comment]
I found a minor issue with the current code. If you create a second list screen (which uses the same relationship as the first), then the message beside the data-entry screen will be displayed twice. It should only display once.

**Comment by MORich-1** [comment]
Ahh yes, I thought I had tested multiple forms and it only showed up the once, my apologies! Ill have it fixed this evening.

**Comment by MORich-1** [comment]
There, I believe that after my application of the latest commit (Boolean) things will progress smoothly. I tried with up to 3 list screens, and only one warning popped up.

:+1:

**Pull request merged**
