### PR TITLE
Clone forms refactor

### PR DESCRIPTION
**Pull request by susannahkirby**

### CODE REVIEW

**Comment by eikonos** [comment]
This works for me. I cloned a couple forms, and the new forms appear, along with screens. Is there an issue when you clone a form?

**Comment by susannahkirby** [comment]
It does work for me as pushed. Did you try switching which lines are commented out? When I make the call to 
> $listScreenHandler->setDefaultListScreenVars($screen, $defaultFormScreenId, $newtitle, $newfid);
(line 1265 in forms.php), I get the error.

**Comment by eikonos** [comment]
The setDefaultListScreenVars() function exists in formScreen.php, but that there isn't a corresponding function with that name in the listOfEntriesScreen.php file.

**Comment by susannahkirby** [comment]
Oh, of course! I see - I had that method in formScreen.php and not listOfEntriesScreen.php. Thanks, it's working now.

**Pull request merged**
